### ISSUE TITLE
`UsesUpdatedStructs()` breaks compatibility with versions of AE prior to 1.16.629

### ISSUE THREAD

**Issue by WaterFace** [shad0wshayd3/HelpExtender#1]
See https://github.com/ianpatt/skse64/blob/09f520a2433747f33ae7d7c15b1164ca198932c3/skse64/PluginAPI.h#L308, 
setting that flag breaks compatibility with earlier versions of AE. However, as far as I can tell this mod doesn't touch the updated structs, so you can replace `v.UsesUpdatedStructs()` with `v.UsesNoStructs()`

**Comment by shad0wshayd3** [comment]
It's using both `TESObjectREFR` and `TESObjectCELL`, which were both affected by `ExtraDataList` changing.

**Comment by WaterFace** [comment]
What commands would cause an issue with that? I'm working on a CommonLibSSE-NG port and that would be helpful for testing.

**Comment by WaterFace** [comment]
Try out my fork: https://github.com/WaterFace/HelpExtender
it's compiling, and the dll produced works on SE and AE, pre- and post- 1.16.629. I'll can submit a pull request if you'd like, once it's clear that the struct changes haven't broken anything

**Comment by shad0wshayd3** [comment]
I don't want to swap any of my projects to NG.
